# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d20b1a63d87f928957d74daf41c5a961"
name = "onchainads"
handle = "onchainads"
application_url = "https://customers-valentine-ci-harassment.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-b891c333.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://customers-valentine-ci-harassment.trycloudflare.com/auth/callback",
  "https://customers-valentine-ci-harassment.trycloudflare.com/auth/shopify/callback",
  "https://customers-valentine-ci-harassment.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
